Repository dandi/dandi-cli, pull requests merged in 2020-12, with the labels that each got.

#284 BF: add h5py.__version__ into the list of tokens for caching
  dandi/pynwb_utils.py
Labels: patch, release

#292 Fix more of publish-schemata workflow
  .github/workflows/publish-schemata.yml
Labels: internal

#293 ls - avoid workaround, more consistent reporting of errors
  dandi/cli/cmd_ls.py
  dandi/cli/formatter.py
  dandi/pynwb_utils.py
  setup.cfg
Labels: UX, enhancement, patch

#226 Function for converting NWB file to AssetMeta instance
  dandi/metadata.py
  dandi/models.py
  dandi/tests/fixtures.py
  dandi/tests/test_metadata.py
  dandi/tests/test_validate.py
  dandi/validate.py
Labels: enhancement, minor

#297 Test against & support Python 3.9
  .github/workflows/test.yml
  setup.cfg
Labels: patch

#296 Replace askyesno() with click.confirm()
  dandi/girder.py
  dandi/support/tests/test_ui.py
  dandi/support/ui.py
  dandi/tests/test_girder.py
Labels: patch

#303 Temporary workaround: prevent upload of files larger than 67108864000
  dandi/upload.py
Labels: bug, release

#304 Autogenerate schema element titles
  dandi/models.py
  dandi/tests/test_models.py
  dandi/tests/test_utils.py
  dandi/utils.py
Labels: patch

#310 Set chunk size on per-file basis; limit to 1000 chunks; upload files up to 400GB ATM
  dandi/girder.py
  dandi/upload.py
Labels: bug, minor, release

#314 Close a file in a test case
  dandi/tests/test_organize.py
Labels: internal

#315 Install hdf5 for Python 3.9 tests
  .github/workflows/test.yml
Labels: internal

#283 Update for new API at https://api.dandiarchive.org/api
  dandi/consts.py
  dandi/dandiapi.py
  dandi/tests/data/dandiarchive-docker/docker-compose.yml
  dandi/tests/fixtures.py
  dandi/tests/test_dandiapi.py
Labels: patch

#318 Tee all logs to user log directory
  dandi/cli/base.py
  dandi/cli/command.py
Labels: patch

#326 Require keyring backends to be initialized before running any tests
  dandi/tests/test_girder.py
Labels: internal
