Repository dandi/dandi-cli, pull requests merged in 2020-11, with the labels that each got.

#265 Use oldest file when race condition causes multiple files per item
  dandi/girder.py
Labels: patch, release

#257 Set up workflow with auto for releasing & PyPI uploads
  .autorc
  .github/workflows/release.yml
  CHANGELOG.md
  DEVELOPMENT.md
Labels: internal

#266 Remove unused link from CHANGELOG.md
  CHANGELOG.md
Labels: documentation, release

#267 Make keyring lookup more flexible
  dandi/girder.py
  dandi/support/tests/test_ui.py
  dandi/support/ui.py
  dandi/tests/test_girder.py
  setup.cfg
Labels: patch

#269 Copy files with `cp --reflink=auto` where supported
  dandi/utils.py
Labels: patch

#272 Add healthchecks for the Postgres and minio Docker containers
  dandi/tests/data/dandiarchive-docker/docker-compose.yml
Labels: internal

#271 Include item path in "Multiple files found for item" message
  dandi/girder.py
Labels: patch

#275 Support h5py 3.0
  dandi/pynwb_utils.py
  setup.cfg
  tox.ini
Labels: patch, release

#279 DOC: strip away duplicate with the handbook information
  README.md
Labels: documentation, internal

#276 Add workflow for publishing model schemata to dandi/schema
  .github/workflows/publish-schemata.yml
  tools/pubschemata.py
Labels: internal

#285 Add rudimentary duecredit support using zenodo's dandi-cli DOI
  dandi/__init__.py
  dandi/due.py
  setup.cfg
Labels: enhancement, minor

#287 updated just models
  dandi/models.py
Labels: internal
