Repository dandi/dandi-cli, pull requests merged in 2021-03, with the labels that each got.

#437 Retry requests on ConnectionErrors
  dandi/dandiapi.py
Labels: patch

#438 Discard empty "sex" and "species" fields on conversion
  dandi/metadata.py
Labels: patch

#442 Eliminate DANDI_SCHEMA; add get_schema_version()
  dandi/metadata.py
  dandi/models.py
  dandi/tests/test_validate.py
  dandi/validate.py
Labels: patch

#443 Check out dandi/dandi-api-datasets with direct `git clone`
  .github/workflows/test-populate-dandiset-yaml.yml
Labels: internal

#440 Eliminate check for session_start_time preceding date_of_birth
  dandi/metadata.py
Labels: patch

#444 Simplify release workflow
  .autorc
  .github/workflows/release.yml
Labels: internal

#446 Cache the individual functions called by validate_file()
  dandi/pynwb_utils.py
  dandi/validate.py
Labels: internal

#445 Add --new-schema option to `ls` command for converting output
  dandi/cli/cmd_ls.py
  dandi/dandiset.py
  dandi/metadata.py
Labels: patch

#452 Add dateModified to asset metadata
  dandi/dandiapi.py
  dandi/download.py
  dandi/metadata.py
  dandi/models.py
  dandi/tests/test_dandiapi.py
  dandi/tests/test_upload.py
  dandi/upload.py
Labels: patch, release

#457 ENH: more of lgr.debug for multipart upload
  dandi/dandiapi.py
Labels: patch

#459 Display `dandi validate` errors using logger
  dandi/cli/cmd_validate.py
Labels: patch

#462 Fix "%s: ok" log message from `dandi validate`
  dandi/cli/cmd_validate.py
Labels: patch

#471 Add `-vv` option to `auto shipit`
  .github/workflows/release.yml
Labels: internal

#468 Only call logging.basicConfig() when used as a command
  dandi/__init__.py
  dandi/cli/command.py
Labels: patch

#460 Change BareAssetMeta.digest to a list
  dandi/consts.py
  dandi/dandiapi.py
  dandi/metadata.py
  dandi/models.py
  dandi/tests/test_metadata.py
Labels: minor

#473 Script for generating S3 versioned file stats
  tools/s3-gc-stats
Labels: internal

#476 Add --devel-debug to `dandi validate`
  dandi/cli/cmd_validate.py
  dandi/pynwb_utils.py
  dandi/validate.py
Labels: patch

#474 ENH: prototype for the DANDIEtag "digester"
  README.md
  dandi/core/__init__.py
  dandi/core/digests/__init__.py
  dandi/core/digests/dandietag.py
  dandi/core/digests/tests/__init__.py
  dandi/core/digests/tests/test_dandietag.py
  dandi/support/digests.py
Labels: minor

#480 Add "digest" command
  dandi/cli/cmd_digest.py
  dandi/cli/command.py
  dandi/cli/tests/test_digest.py
Labels: minor

#481 Add dandi_etag digest type to schema
  dandi/consts.py
  dandi/model_types.py
  dandi/models.py
  dandi/tests/test_metadata.py
  dandi/tests/test_models.py
Labels: patch

#486 Remove "current" column from upload progress display
  dandi/upload.py
Labels: patch, release

#491 Don't hardcode DANDI_SCHEMA_VERSION value in tests
  dandi/tests/test_metadata.py
Labels: tests

#489 dandi ls: Error if --schema is given with remote resource of different version
  dandi/cli/cmd_ls.py
Labels: patch

#479 Update upload code for changes in API
  dandi/core/digests/dandietag.py
  dandi/dandiapi.py
  dandi/download.py
  dandi/pynwb_utils.py
  dandi/support/digests.py
  dandi/tests/test_upload.py
  dandi/upload.py
Labels: patch

#496 Check for already-uploaded blobs via /uploads/initialize/ instead of /blobs/digest/
  dandi/dandiapi.py
Labels: patch

#495 Validate uploads before digesting
  dandi/upload.py
Labels: patch

#493 Lowercase "sha256"
  dandi/model_types.py
  dandi/tests/test_models.py
Labels: patch

#500 Add option for only running new Dandi API tests
  .github/workflows/test.yml
  dandi/conftest.py
Labels: release, tests

#499 Upload file parts in parallel
  dandi/cli/cmd_upload.py
  dandi/core/digests/dandietag.py
  dandi/dandiapi.py
  dandi/upload.py
Labels: patch

#507 Ignore warnings from ruamel.yaml caused by hdmf using deprecated functions
  tox.ini
Labels: tests

#506 Run "provision" container in the foreground
  dandi/tests/fixtures.py
Labels: tests

#511 Add --only-metadata option to migrate-dandisets.py
  tools/migrate-dandisets.py
Labels: internal

#519 Fix typo in setting jobs_per_file for upload command
  dandi/cli/cmd_upload.py
Labels: patch

#509 Add "delete" command
  dandi/cli/cmd_delete.py
  dandi/cli/cmd_ls.py
  dandi/cli/command.py
  dandi/dandiapi.py
  dandi/delete.py
  dandi/tests/data/dandiarchive-docker/docker-compose.yml
  dandi/tests/fixtures.py
  dandi/tests/test_dandiapi.py
  dandi/tests/test_delete.py
  dandi/tests/test_upload.py
  dandi/utils.py
Labels: minor

#523 Better filtering of file-only log messages
  dandi/cli/command.py
Labels: patch

#521 Retry requests that fail with 503
  dandi/dandiapi.py
  dandi/girder.py
  dandi/utils.py
  setup.cfg
Labels: patch

#517 ENH: Enhancements to metadata schema and compatibility with JSONLD
  dandi/consts.py
  dandi/dandiapi.py
  dandi/download.py
  dandi/metadata.py
  dandi/model_types.py
  dandi/models.py
  dandi/tests/test_metadata.py
  dandi/tests/test_models.py
  dandi/upload.py
Labels: internal

#525 Store metadata test JSON in files
  dandi/tests/data/metadata/dandimeta_migration.new.json
  dandi/tests/data/metadata/dandimeta_migration.old.json
  dandi/tests/data/metadata/metadata2asset.json
  dandi/tests/data/metadata/metadata2asset_simple1.json
  dandi/tests/test_metadata.py
  setup.cfg
Labels: tests

#528 Fix retrying 503's
  dandi/dandiapi.py
  dandi/utils.py
Labels: patch
