Repository dandi/dandi-cli, pull requests merged in 2021-02, with the labels that each got.

#342 BF: allow to handle an item with multiple files
  dandi/upload.py
Labels: patch

#353 Configure & apply isort via pre-commit
  .pre-commit-config.yaml
  README.md
  dandi/__init__.py
  dandi/cli/base.py
  dandi/cli/cmd_download.py
  dandi/cli/cmd_ls.py
  dandi/cli/cmd_organize.py
  dandi/cli/cmd_validate.py
  dandi/cli/command.py
  dandi/cli/formatter.py
  dandi/cli/tests/test_command.py
  dandi/cli/tests/test_download.py
  dandi/dandiapi.py
  dandi/dandiarchive.py
  dandi/dandiset.py
  dandi/download.py
  dandi/due.py
  dandi/girder.py
  dandi/metadata.py
  dandi/models.py
  dandi/organize.py
  dandi/pynwb_utils.py
  dandi/register.py
  dandi/support/cache.py
  dandi/support/digests.py
  dandi/support/generatorify.py
  dandi/support/iterators.py
  dandi/support/pyout.py
  dandi/support/tests/test_cache.py
  dandi/support/tests/test_digests.py
  dandi/support/tests/test_iterators.py
  dandi/tests/fixtures.py
  dandi/tests/test_dandiapi.py
  dandi/tests/test_dandiarchive.py
  dandi/tests/test_download.py
  dandi/tests/test_girder.py
  dandi/tests/test_metadata.py
  dandi/tests/test_models.py
  dandi/tests/test_organize.py
  dandi/tests/test_pynwb_utils.py
  dandi/tests/test_register.py
  dandi/tests/test_upload.py
  dandi/tests/test_utils.py
  dandi/upload.py
  dandi/utils.py
  dandi/validate.py
  pyproject.toml
  tools/instantiate-dandisets.py
  tools/pubschemata.py
Labels: internal

#348 Update and simplify models to support automated editor generation
  dandi/dandiset.py
  dandi/metadata.py
  dandi/models.py
  dandi/tests/fixtures.py
  dandi/tests/test_metadata.py
  dandi/tests/test_validate.py
  setup.cfg
Labels: minor

#356 Fix numpy dependency issue in tests
  .github/workflows/test.yml
Labels: internal

#354 Add DANDI_TESTS_PERSIST_DOCKER_COMPOSE envvar for reusing Docker containers across test runs
  DEVELOPMENT.md
  dandi/tests/fixtures.py
Labels: internal

#346 Give AssetMeta and DandiMeta `json_dict()` methods for better dictification
  dandi/models.py
  dandi/upload.py
Labels: patch

#363 Add workflow for running populate_dandiset_yaml.py
  .github/workflows/test-populate-dandiset-yaml.yml
Labels: internal

#364 Adjust license metadata conversion
  dandi/metadata.py
  dandi/tests/test_metadata.py
Labels: patch

#347 Handle uploading already-present files in new API
  dandi/dandiapi.py
  dandi/tests/test_dandiapi.py
  dandi/tests/test_upload.py
  dandi/upload.py
Labels: patch

#366 Add script for migrating Dandiset metadata
  tools/migrate-dandisets.py
Labels: internal

#374 Discard invalid asset identifiers when extracting metadata
  dandi/metadata.py
Labels: patch

#378 Add `include_metadata=False` parameter to asset-listing DandiAPIClient methods
  dandi/dandiapi.py
  dandi/dandiarchive.py
  dandi/tests/test_dandiapi.py
Labels: patch

#377 Support downloading folders and latest Dandiset version
  dandi/dandiarchive.py
  dandi/download.py
  dandi/tests/test_dandiapi.py
  dandi/tests/test_dandiarchive.py
  dandi/tests/test_download.py
Labels: patch

#381 List extra auto labels in DEVELOPMENT.md
  DEVELOPMENT.md
Labels: documentation

#379 Give `validate` command a `--schema VERSION` option for validating assets and dandiset.yaml
  dandi/cli/cmd_validate.py
  dandi/validate.py
Labels: patch

#382 Set asset path via metadata only
  dandi/dandiapi.py
  dandi/tests/test_dandiapi.py
  dandi/upload.py
Labels: internal

#383 Make `dandi download -i <instance>` run in a Dandiset download that Dandiset
  dandi/cli/cmd_download.py
  dandi/cli/tests/test_download.py
Labels: patch

#384 Give known_urls human-readable display strings
  dandi/dandiarchive.py
Labels: patch

#388 Support passing precomputed file digest to DandiAPIClient upload methods
  dandi/dandiapi.py
  dandi/upload.py
Labels: internal

#390 Make existing="refresh" a synonym for "overwrite" for new upload
  dandi/tests/test_upload.py
  dandi/upload.py
Labels: patch

#391 Cache file digests and check for change in digest when uploading
  dandi/dandiapi.py
  dandi/support/digests.py
  dandi/upload.py
Labels: patch

#394 Use PUT endpoint to replace pre-existing assets on upload
  dandi/dandiapi.py
  dandi/upload.py
Labels: internal

#397 Use fscacher
  dandi/pynwb_utils.py
  dandi/support/cache.py
  dandi/support/digests.py
  dandi/support/tests/test_cache.py
  setup.cfg
Labels: internal

#399 Add CI run with dev version of pynwb
  .github/workflows/test.yml
Labels: tests

#401 Disabling logging to stderr while using pyout
  dandi/cli/formatter.py
  dandi/download.py
  dandi/support/pyout.py
  dandi/upload.py
Labels: patch

#386 Populate wasDerivedFrom
  dandi/metadata.py
  dandi/tests/test_metadata.py
Labels: patch

#408 Sleep increasing amounts while waiting for uploaded assets to validate
  dandi/dandiapi.py
Labels: patch

#412 Add more logging when uploading & downloading
  dandi/dandiapi.py
Labels: patch

#409 Set Content-MD5 header when uploading asset parts
  dandi/dandiapi.py
  dandi/tests/test_dandiapi.py
Labels: patch

#413 Capture all dandi log messages when testing
  dandi/tests/fixtures.py
Labels: tests

#415 Add test of upload of large file to new API
  dandi/tests/test_dandiapi.py
Labels: tests

#417 upload(): Only yield first "validating" status to pyout
  dandi/upload.py
Labels: patch

#419 Revert PR #409 (Content-MD5 header)
  dandi/dandiapi.py
  dandi/tests/test_dandiapi.py
Labels: patch

#418 Log failed HTTP connections; include PID and TID in logs; include asset path in upload log messages
  dandi/cli/command.py
  dandi/dandiapi.py
Labels: patch

#420 Distinguish between pre- and post-validation when uploading
  dandi/dandiapi.py
  dandi/upload.py
Labels: patch

#425 Remove misleading log message about authenticating with new API
  dandi/dandiapi.py
Labels: patch

#424 Report dandi version in User-Agent header
  dandi/dandiapi.py
  dandi/utils.py
Labels: patch

#422 Assorted code cleanup
  dandi/__init__.py
  dandi/dandiset.py
  dandi/tests/test_organize.py
  dandi/utils.py
  setup.cfg
  tox.ini
Labels: internal

#426 Update Black
  .pre-commit-config.yaml
  dandi/__init__.py
  dandi/cli/base.py
  dandi/cli/cmd_ls.py
  dandi/dandiarchive.py
  dandi/dandiset.py
  dandi/download.py
  dandi/girder.py
  dandi/models.py
  dandi/organize.py
  dandi/pynwb_utils.py
  dandi/support/digests.py
  dandi/support/iterators.py
  dandi/tests/skip.py
  dandi/tests/test_dandiapi.py
  dandi/tests/test_upload.py
  dandi/utils.py
  dandi/validate.py
Labels: internal

#423 Use iter_content() instead of raw.stream()
  dandi/dandiapi.py
Labels: internal

#428 Error if sha256 digest is missing from asset being downloaded
  dandi/download.py
Labels: patch

#429 Set DJANGO_DANDI_SCHEMA_VERSION in docker-compose.yml
  dandi/tests/data/dandiarchive-docker/docker-compose.yml
Labels: tests
