Repository dandi/dandi-cli, pull requests merged in 2021-07, with the labels that each got.

#693 Add get_asset_metadata() function
  dandi/metadata.py
  dandi/upload.py
Labels: minor

#669 fix: raise error when unable to parse age and set session name properly
  dandi/metadata.py
  dandi/tests/data/metadata/metadata2asset.json
  dandi/tests/data/metadata/metadata2asset_simple1.json
Labels: patch, release

#705 BF+RF(TST): populate contentUrl to satisfy Asset requirement in 0.5.0
  dandi/tests/test_metadata.py
Labels: tests

#702 Skip shell completion test entirely on Windows
  dandi/cli/tests/test_shell_completion.py
Labels: release, tests

#707 BF(TST): Allow for IteratorWithAggregation to get nothing if reraise_immediately
  dandi/support/tests/test_iterators.py
Labels: tests

#712 ENH: adding sphinx documentation for the dandi-cli
  .github/workflows/docs.yml
  .gitignore
  dandi/dandiapi.py
  dandi/dandiarchive.py
  dandi/tests/skip.py
  docs/Makefile
  docs/demos/basic-workflow1.sh
  docs/make.bat
  docs/requirements.txt
  docs/source/cmdline/delete.rst
  docs/source/cmdline/digest.rst
  docs/source/cmdline/download.rst
  docs/source/cmdline/index.rst
  docs/source/cmdline/ls.rst
  docs/source/cmdline/organize.rst
  docs/source/cmdline/shell-completion.rst
  docs/source/cmdline/upload.rst
  docs/source/cmdline/validate.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/modref/consts.rst
  docs/source/modref/dandiapi.rst
  docs/source/modref/dandiarchive.rst
  docs/source/modref/index.rst
  docs/source/modref/support.digests.rst
  docs/source/modref/utils.rst
  tox.ini
Labels: documentation

#715 Add Readthedocs config
  .readthedocs.yaml
Labels: internal

#716 Increase retries & wait times for API errors
  dandi/dandiapi.py
Labels: patch, release

#718 Install "test" extras when building docs
  .readthedocs.yaml
  tox.ini
Labels: documentation

#720 Set "version" in docs/source/conf.py
  docs/source/conf.py
Labels: documentation

#721 Stretch the doc to the screen width
  docs/source/_static/custom.css
  docs/source/conf.py
Labels: documentation

#725 ENH: exit with non-0 when "bad_version" of dandi-cli is used
  dandi/cli/command.py
  setup.cfg
Labels: UX, patch

#724 Make upload() fail if client & server schema versions are not in sync
  dandi/dandiapi.py
  dandi/exceptions.py
  dandi/tests/test_dandiapi.py
  dandi/upload.py
Labels: minor

#728 Invoke etelemetry when constructing a DandiAPIClient; honor DANDI_NO_ET
  dandi/cli/command.py
  dandi/dandiapi.py
  dandi/utils.py
Labels: minor

#733 RF: attempt nwb metadata extraction only on .nwb, if fails -- warning
  dandi/metadata.py
Labels: minor

#734 Retry following redirects that return 404
  dandi/dandiarchive.py
Labels: patch

#737 Log "error" statuses while uploading as ERROR log messages
  dandi/upload.py
Labels: UX, patch

#676 Python API rewrite, part 2
  .github/workflows/test.yml
  dandi/consts.py
  dandi/dandiapi.py
  dandi/dandiarchive.py
  dandi/delete.py
  dandi/tests/test_dandiapi.py
  dandi/tests/test_delete.py
  dandi/tests/test_download.py
  dandi/tests/test_upload.py
  dandi/tests/test_utils.py
  dandi/upload.py
  dandi/utils.py
  setup.cfg
  tox.ini
Labels: minor, release

#740 Test RemoteDandiset.refresh()
  dandi/dandiapi.py
  dandi/tests/test_dandiapi.py
Labels: tests

#741 Rename get_assets_under_path() to get_assets_with_path_prefix()
  dandi/dandiapi.py
  dandi/dandiarchive.py
  dandi/delete.py
  dandi/upload.py
Labels: minor

#742 Correctly set User-Agent for client requests
  dandi/dandiapi.py
Labels: patch

#744 Pin rabbitmq version
  dandi/tests/data/dandiarchive-docker/docker-compose.yml
Labels: tests

#746 Test against rc/2.0.0 branch of pynwb
  .github/workflows/test.yml
Labels: tests

#747 Restore the rabbitmq version
  dandi/tests/data/dandiarchive-docker/docker-compose.yml
Labels: dependencies, severity-minor, tests
