Repository dandi/dandi-cli, pull requests merged in 2021-04, with the labels that each got.

#536 Give `ls` a `--metadata` option
  dandi/cli/cmd_ls.py
Labels: patch

#535 Support parsing & navigating asset download URLs
  dandi/dandiarchive.py
  dandi/tests/test_dandiarchive.py
Labels: patch

#537 Update dandiarchive client to use most_recent_published_version
  dandi/dandiarchive.py
Labels: patch, release

#546 Log errors in extracting metadata for upload
  dandi/upload.py
Labels: patch

#549 small fix of extract_sex
  dandi/metadata.py
Labels: patch

#545 Log dandi, hdmf, h5py, and pynwb versions to log file
  dandi/cli/command.py
Labels: patch

#551 DOC: minor tune up to README.md on installation instructions and WiP
  README.md
Labels: documentation, release

#553 Get hdmf, pynwb, h5py versions without importing
  dandi/cli/command.py
  dandi/utils.py
Labels: patch, performance

#555 Support "…/assets/?path=<path>" URLs
  dandi/dandiarchive.py
  dandi/tests/test_dandiarchive.py
Labels: patch

#556 Refresh dandiset.yaml on download if out of date
  dandi/download.py
Labels: patch

#559 Strip trailing slash from API URL used by delete()
  dandi/delete.py
Labels: patch

#561 Fix & test for downloading by asset ID URL
  dandi/download.py
  dandi/tests/test_download.py
Labels: patch

#563 Error with a decent message when trying to delete() a path not in a Dandiset
  dandi/delete.py
  dandi/tests/test_delete.py
Labels: patch

#564 Fix a typo in the display string for one of the known URL patterns
  dandi/dandiarchive.py
Labels: patch

#567 BF: do not assume that service record of redirector is present/has url
  dandi/utils.py
Labels: patch, release

#571 Add further tests of get_instance() and server-info
  dandi/tests/test_utils.py
Labels: tests

#565 Switch default dandi instance to dandi-api based on redirector
  dandi/dandiarchive.py
  dandi/delete.py
  dandi/tests/test_dandiarchive.py
  dandi/tests/test_utils.py
  dandi/utils.py
Labels: minor

#560 Models: define id, add various additional types (genotype, etc), boost model version to 0.3.0
  dandi/consts.py
  dandi/metadata.py
  dandi/model_types.py
  dandi/models.py
  dandi/tests/data/metadata/dandimeta_migration.new.json
  dandi/tests/data/metadata/metadata2asset.json
  dandi/tests/data/metadata/metadata2asset_simple1.json
  dandi/tests/test_metadata.py
  dandi/tests/test_models.py
Labels: minor, release, schema

#579 Log validation errors
  dandi/cli/cmd_validate.py
  dandi/pynwb_utils.py
  dandi/validate.py
Labels: patch

#575 Update for the version /info endpoint in dandi-api
  dandi/dandiapi.py
Labels: patch, release

#582 Add codespell
  .pre-commit-config.yaml
  CHANGELOG.md
  dandi/cli/base.py
  dandi/cli/cmd_organize.py
  dandi/download.py
  dandi/models.py
  dandi/tests/fixtures.py
  dandi/tests/test_utils.py
  dandi/utils.py
  setup.cfg
  tox.ini
Labels: internal

#585 Retry upload requests that result in 500 responses
  dandi/dandiapi.py
Labels: patch

#591 BF: "girder" record might be there but "url" might be None
  dandi/tests/test_dandiarchive.py
  dandi/tests/test_delete.py
  dandi/utils.py
Labels: bug, patch, release

#594 Give "delete" a --skip-missing option
  dandi/cli/cmd_delete.py
  dandi/delete.py
  dandi/tests/test_delete.py
Labels: minor

#589 a script to validate dandi-api collection listing against girder
  tools/validate-api-against-girder.py
Labels: internal

#602 Recognize "DANDI:<identifier>" strings as URL-likes
  dandi/utils.py
Labels: patch

#601 Include list of supported URL patterns in `dandi ls --help`
  dandi/cli/cmd_ls.py
  dandi/dandiarchive.py
Labels: patch

#588 Remove Girder support
  .github/workflows/test.yml
  DEVELOPMENT.md
  dandi/cli/base.py
  dandi/cli/cmd_ls.py
  dandi/cli/cmd_register.py
  dandi/cli/cmd_upload.py
  dandi/cli/command.py
  dandi/consts.py
  dandi/dandiapi.py
  dandi/dandiarchive.py
  dandi/delete.py
  dandi/download.py
  dandi/girder.py
  dandi/keyring.py
  dandi/register.py
  dandi/tests/data/dandiarchive-docker/docker-compose.yml
  dandi/tests/fixtures.py
  dandi/tests/test_dandiarchive.py
  dandi/tests/test_delete.py
  dandi/tests/test_download.py
  dandi/tests/test_keyring.py
  dandi/tests/test_register.py
  dandi/tests/test_upload.py
  dandi/tests/test_utils.py
  dandi/upload.py
  dandi/utils.py
  setup.cfg
Labels: minor

#603 Remove numpy pre-pinning in test.yml
  .github/workflows/test.yml
  tox.ini
Labels: tests

#604 Remove unused functions (and other cleanups)
  dandi/cli/base.py
  dandi/cli/cmd_ls.py
  dandi/cli/cmd_upload.py
  dandi/consts.py
  dandi/dandiarchive.py
  dandi/dandiset.py
  dandi/upload.py
  dandi/utils.py
Labels: minor

#581 Support specifying the dandi redirector via an env var
  dandi/consts.py
  dandi/tests/fixtures.py
  dandi/tests/test_dandiarchive.py
  dandi/tests/test_utils.py
  tox.ini
Labels: internal, release

#605 Restructure parse_dandi_url() return type
  dandi/cli/cmd_download.py
  dandi/cli/cmd_ls.py
  dandi/cli/tests/test_ls.py
  dandi/dandiarchive.py
  dandi/delete.py
  dandi/download.py
  dandi/tests/test_dandiarchive.py
  dandi/tests/test_delete.py
Labels: minor
