Repository dandi/dandi-cli, pull requests merged in 2021-06, with the labels that each got.

#646 Change `download --existing` default to "error"; add "overwrite-different" option; handle git-annex repos
  dandi/cli/cmd_download.py
  dandi/cli/tests/test_download.py
  dandi/download.py
Labels: minor

#654 dandi ls: Make json and json_pp formats output arrays; add json_lines for old json format
  dandi/cli/cmd_ls.py
  dandi/cli/formatter.py
  dandi/cli/tests/test_formatter.py
  dandi/cli/tests/test_ls.py
Labels: minor

#655 Reprompt or fail on attempt to use an invalid API token
  dandi/dandiapi.py
  dandi/tests/test_dandiapi.py
Labels: minor, release

#656 Update pre-commit repo versions and configure isort to properly handle "from . import" lines
  .pre-commit-config.yaml
  dandi/cli/base.py
  dandi/cli/cmd_digest.py
  dandi/cli/cmd_ls.py
  dandi/cli/command.py
  dandi/dandiapi.py
  dandi/dandiarchive.py
  dandi/dandiset.py
  dandi/download.py
  dandi/exceptions.py
  dandi/metadata.py
  dandi/organize.py
  dandi/pynwb_utils.py
  dandi/support/pyout.py
  dandi/tests/fixtures.py
  dandi/tests/test_dandiapi.py
  dandi/tests/test_utils.py
  dandi/upload.py
  dandi/utils.py
  dandi/validate.py
  pyproject.toml
Labels: internal

#657 Address LGTM alerts
  dandi/__init__.py
  dandi/cli/__init__.py
  dandi/conftest.py
  dandi/metadata.py
  dandi/support/generatorify.py
  dandi/support/iterators.py
  lgtm.yml
  tools/instantiate-dandisets.py
  tools/validate-api-against-girder.py
Labels: internal

#644 ENH: more metadata to reconstruct filename, upgrade to use dandischema 0.2.3 (schema 0.4.0)
  dandi/cli/cmd_ls.py
  dandi/metadata.py
  dandi/tests/data/metadata/dandimeta_migration.new.json
  dandi/tests/data/metadata/metadata2asset.json
  dandi/tests/data/metadata/metadata2asset_simple1.json
  dandi/tests/test_metadata.py
  dandi/validate.py
  setup.cfg
Labels: minor

#667 Run test workflow on pushes only on master
  .github/workflows/test.yml
Labels: internal

#666 ls --schema: Calculate digest for local assets
  dandi/cli/cmd_ls.py
  dandi/cli/tests/test_ls.py
Labels: patch, release

#660 Python API rewrite, part 1
  dandi/cli/cmd_ls.py
  dandi/dandiapi.py
  dandi/dandiarchive.py
  dandi/delete.py
  dandi/download.py
  dandi/tests/fixtures.py
  dandi/tests/test_dandiapi.py
  dandi/tests/test_download.py
  dandi/tests/test_upload.py
  dandi/upload.py
Labels: minor

#675 Add RemoteAsset.get_content_url() method
  dandi/dandiapi.py
  dandi/tests/test_dandiapi.py
Labels: minor

#679 Don't pass "asset" field from upload iterator to pyout
  dandi/upload.py
Labels: patch

#680 Fix a failing test on Windows on conda-forge
  dandi/cli/tests/test_shell_completion.py
Labels: release, tests

#684 Remove references to "dandi register" command
  dandi/cli/cmd_upload.py
  dandi/delete.py
  dandi/tests/test_delete.py
  dandi/upload.py
Labels: patch

#681 Fix a failing test on Windows on conda-forge (again)
  dandi/cli/cmd_shell_completion.py
Labels: patch

#686 changing unitText
  dandi/metadata.py
  dandi/tests/data/metadata/metadata2asset.json
Labels: patch

#683 Create valid Dandiset metadata when testing; create valid asset metadata for non-NWB files; wait for validation before publishing
  dandi/dandiapi.py
  dandi/metadata.py
  dandi/tests/data/dandiarchive-docker/docker-compose.yml
  dandi/tests/fixtures.py
  dandi/tests/test_dandiapi.py
  dandi/tests/test_utils.py
  dandi/utils.py
Labels: patch

#691 Adjust RemoteAsset.json_dict()
  dandi/dandiapi.py
  dandi/tests/test_dandiapi.py
Labels: minor

#687 Increase minimum dandischema version to 0.2.9
  .et
  dandi/tests/test_dandiapi.py
  setup.cfg
Labels: dependencies, release
