Repository dandi/dandi-cli, pull requests merged in 2021-08, with the labels that each got.

#748 Support `/asset/<asset id>/download/` URLs
  dandi/dandiapi.py
  dandi/dandiarchive.py
  dandi/tests/test_dandiarchive.py
  dandi/tests/test_download.py
Labels: minor, release

#749 Boost dandischema to ~= 0.3.1 as it provides dandischema 0.5.1 required by dandi-api
  setup.cfg
Labels: patch, release

#754 Remove test against rc/2.0.0 branch of pynwb
  .github/workflows/test.yml
Labels: tests

#753 Give API resource classes `__str__` methods
  dandi/dandiapi.py
  dandi/tests/test_dandiapi.py
Labels: minor

#760 Add dandischema into fscacher tokens for validate
  dandi/pynwb_utils.py
Labels: patch

#763 Use new published version of 000027 in tests
  dandi/tests/test_download.py
Labels: tests
