Repository dandi/dandi-cli, pull requests merged in 2021-05, with the labels that each got.

#610 Cut down on some code duplication in delete.py
  dandi/delete.py
Labels: internal

#609 DOC: Extend description for delete to point that it could be URL etc
  dandi/cli/cmd_delete.py
Labels: UX, patch

#612 Make test_server_info use Docker fixture if DANDI_REDIRECTOR_BASE is set
  dandi/tests/test_utils.py
Labels: release, tests

#615 RF: organize - should no longer alter dandiset.yaml
  dandi/cli/cmd_organize.py
  dandi/tests/test_organize.py
Labels: minor

#621 Add dandi-staging to known_instances
  dandi/consts.py
Labels: patch

#616 Add "sync" option for upload & download
  dandi/cli/cmd_download.py
  dandi/cli/cmd_upload.py
  dandi/cli/tests/test_download.py
  dandi/download.py
  dandi/tests/fixtures.py
  dandi/tests/test_download.py
  dandi/tests/test_upload.py
  dandi/upload.py
  dandi/utils.py
  setup.cfg
Labels: minor

#637 Make the "#/" in GUI URLs optional
  dandi/dandiarchive.py
  dandi/tests/test_dandiarchive.py
Labels: patch

#636 Allow trailing slash in GUI URLs
  dandi/dandiarchive.py
  dandi/tests/test_dandiarchive.py
Labels: patch, release

#623 REF: updated model requirements
  .github/workflows/test-schema.yml
  dandi/consts.py
  dandi/dandiset.py
  dandi/metadata.py
  dandi/models.py
  dandi/tests/data/metadata/dandimeta_migration.new.json
  dandi/tests/data/metadata/dandimeta_migration.old.json
  dandi/tests/data/metadata/metadata2asset.json
  dandi/tests/data/metadata/metadata2asset_simple1.json
  dandi/tests/test_metadata.py
  dandi/tests/test_models.py
  dandi/validate.py
Labels: minor, schema

#596 adding to_datacite method
  .github/workflows/test.yml
  dandi/models.py
  dandi/tests/data/metadata/meta_000004.json
  dandi/tests/data/metadata/meta_000008.json
  dandi/tests/test_models.py
Labels: patch

#640 Add "shell-completion" command
  dandi/cli/cmd_shell_completion.py
  dandi/cli/command.py
  dandi/cli/tests/test_shell_completion.py
  setup.cfg
Labels: minor

#643 Move schema code to dandischema
  .github/workflows/publish-schemata.yml
  .github/workflows/test-schema.yml
  dandi/cli/cmd_ls.py
  dandi/consts.py
  dandi/dandiset.py
  dandi/metadata.py
  dandi/model_types.py
  dandi/models.py
  dandi/tests/data/metadata/meta_000004.json
  dandi/tests/data/metadata/meta_000008.json
  dandi/tests/test_metadata.py
  dandi/tests/test_models.py
  dandi/tests/test_validate.py
  dandi/validate.py
  setup.cfg
  tools/pubschemata.py
Labels: minor

#645 Delete name2title()
  dandi/tests/test_utils.py
  dandi/utils.py
Labels: patch

#647 Warn on ignored symlinks to directories
  dandi/utils.py
Labels: patch

#648 Include CHANGELOG.md and tox.ini in sdists
  MANIFEST.in
Labels: internal

#650 Pin dandischema to compatible 0.minor version
  setup.cfg
Labels: patch, release

#649 Set `auto` author to "DANDI Bot"
  .autorc
Labels: internal
