Repository dandi/dandi-cli, pull requests merged in 2022-02, with the labels that each got.

#893 Cancel a Zarr upload if an error occurs partway through
  dandi/files.py
Labels: patch

#895 Make use of `/assets/{asset_id}/info/` endpoint
  dandi/dandiapi.py
  dandi/download.py
  dandi/tests/test_download.py
  docs/source/modref/dandiapi.rst
Labels: minor

#898 Pin minio image version
  dandi/tests/data/dandiarchive-docker/docker-compose.yml
Labels: tests

#899 Make `paths` argument to `upload()` optional
  dandi/tests/fixtures.py
  dandi/upload.py
Labels: internal

#841 Video files organize
  dandi/cli/cmd_organize.py
  dandi/consts.py
  dandi/organize.py
  dandi/pynwb_utils.py
  dandi/tests/fixtures.py
  dandi/tests/test_metadata.py
  dandi/tests/test_organize.py
  setup.cfg
  tox.ini
Labels: minor

#901 Document new `dandi organize` options in Read the Docs site
  dandi/cli/cmd_organize.py
  docs/source/cmdline/organize.rst
Labels: documentation

#900 Add zarr-checksum method to `dandi digest`
  dandi/cli/cmd_digest.py
  dandi/cli/tests/test_digest.py
  dandi/support/digests.py
  docs/source/cmdline/digest.rst
Labels: minor, zarr

#908 Add dedicated HTTP404Error exception class
  dandi/dandiapi.py
  dandi/exceptions.py
Labels: internal

#910 Remove unused tqdm dependency
  setup.cfg
Labels: dependencies

#911 Specify Dandiset ID when creating a Zarr
  dandi/files.py
Labels: patch

#912 Use full asset path as name of Zarr object
  dandi/files.py
Labels: patch

#907 Mint Zarr assets at start of upload and sync Zarr contents
  dandi/consts.py
  dandi/dandiapi.py
  dandi/files.py
  dandi/tests/test_upload.py
  tox.ini
Labels: patch, cmd-upload, zarr

#916 Make `dandi upload` look for dandiset.yaml in parents of common path
  dandi/cli/cmd_upload.py
  dandi/tests/fixtures.py
  dandi/upload.py
  docs/source/cmdline/upload.rst
Labels: patch, release, cmd-upload

#919 Don't repeat API requests when finding subdir files to delete before Zarr upload
  dandi/files.py
Labels: performance, cmd-upload, zarr

#925 Let `dandi delete` take paths to local Zarrs
  dandi/delete.py
  dandi/tests/test_delete.py
Labels: patch, cmd-delete, zarr

#923 Minimize/optimize Zarr digestion when uploading
  dandi/dandiapi.py
  dandi/files.py
  dandi/support/digests.py
  dandi/support/tests/test_digests.py
  dandi/support/threaded_walk.py
  dandi/tests/test_dandiapi.py
  dandi/tests/test_upload.py
  dandi/upload.py
Labels: performance, cmd-upload, zarr
