Repository dandi/dandi-cli, pull requests merged in 2022-04, with the labels that each got.

#945 Black update
  .pre-commit-config.yaml
Labels: internal

#949 Work around a bug in docker-compose
  dandi/tests/fixtures.py
Labels: tests

#953 Specify all queues in test celery worker
  dandi/tests/data/dandiarchive-docker/docker-compose.yml
Labels: tests

#959 Add DANDI_JUPYTERHUB_URL to test docker-compose
  dandi/tests/data/dandiarchive-docker/docker-compose.yml
Labels: minor, release

#960 Fix type in test docker-compose env var
  dandi/tests/data/dandiarchive-docker/docker-compose.yml
Labels: patch, release

#961 Better detection of empty directories when download-syncing Zarrs
  dandi/download.py
  dandi/tests/test_download.py
Labels: patch

#955 Validator fixes: fallback to our version, skip dotdirs on windows, etc
  dandi/bids_validator_xs.py
  dandi/tests/test_bids_validator_xs.py
Labels: patch, release

#964 Combine subtests of `test_publish_and_manipulate`
  dandi/tests/test_dandiapi.py
Labels: tests

#975 Update `test_follow_redirect`
  dandi/tests/test_dandiarchive.py
Labels: tests

#974 Update `test_parse_api_url[DANDI:000027]`
  dandi/tests/test_dandiarchive.py
Labels: tests

#972 Strip trailing slash from URLs in `/server-info`
  dandi/utils.py
Labels: patch

#978 Mark `test_server_info` as xfailing
  dandi/tests/test_utils.py
Labels: tests

#965 Removed duplicate, and simplified bids validator tests
  dandi/tests/test_bids_validator_xs.py
  dandi/tests/test_validate.py
Labels: tests

#982 performance: do not duplicate schema loading
  dandi/bids_validator_xs.py
Labels: patch, performance

#971 keeping logs cleaner in dedicated directory
  dandi/bids_validator_xs.py
  dandi/tests/test_bids_validator_xs.py
Labels: patch

#447 Add new API design doc
  doc/design/python-api-1.md
Labels: internal

#984 Increase Zarr depth limit to 7 directories
  dandi/consts.py
Labels: patch, release, zarr

#986 Remove size comparison check when uploading Zarr entries
  dandi/files.py
Labels: release, performance, cmd-upload, zarr

#985 Whitespace for string returns
  dandi/bids_validator_xs.py
  dandi/cli/cmd_validate.py
Labels: patch, BIDS, cmd-validate
