Repository dandi/dandi-cli, pull requests merged in 2022-09, with the labels that each got.

#1112 BF(workaround): blacklist 23.9.0 of keyring since introduced regression
  setup.cfg
Labels: release, internal

#1116 Test against dev version of keyring package
  .github/workflows/test.yml
Labels: tests

#1115 Detect link type for `organize` by linking from first src dir to dest dir
  dandi/organize.py
  dandi/tests/test_organize.py
Labels: patch, release
