Repository dandi/dandi-cli, pull requests merged in 2022-01, with the labels that each got.

#851 Improve CLI documentation
  dandi/cli/cmd_organize.py
  dandi/cli/cmd_upload.py
  dandi/dandiarchive.py
  docs/source/cmdline/dandi.rst
  docs/source/cmdline/delete.rst
  docs/source/cmdline/digest.rst
  docs/source/cmdline/download.rst
  docs/source/cmdline/index.rst
  docs/source/cmdline/ls.rst
  docs/source/cmdline/organize.rst
  docs/source/cmdline/shell-completion.rst
  docs/source/cmdline/upload.rst
  docs/source/cmdline/validate.rst
  docs/source/index.rst
  docs/source/ref/index.rst
  docs/source/ref/urls.rst
Labels: documentation

#855 Add `embargo_status` to dandiset endpoint
  dandi/consts.py
  dandi/dandiapi.py
  dandi/tests/test_dandiapi.py
Labels: minor

#859 Assorted code cleanups
  dandi/delete.py
  dandi/metadata.py
  dandi/tests/fixtures.py
  dandi/tests/test_metadata.py
  dandi/tests/test_organize.py
  dandi/utils.py
Labels: internal

#860 Add a wrapper function for the calls to `find_files()` in tests
  dandi/tests/test_dandiapi.py
  dandi/tests/test_delete.py
  dandi/tests/test_download.py
  dandi/tests/test_upload.py
  dandi/utils.py
Labels: internal

#861 Replace the use of pyfakefs with a `tmp_home` fixture
  dandi/keyring.py
  dandi/tests/fixtures.py
  dandi/tests/test_keyring.py
  setup.cfg
Labels: tests

#862 Move a comment
  dandi/__init__.py
Labels: release, internal

#863 Include "dandiset" field in /uploads/initialize/ requests
  dandi/dandiapi.py
Labels: minor, release

#868 upgrade dandischema requirement from 0.4.1 to 0.5.1 (~=)
  setup.cfg
Labels: release, dependencies

#866 Update bad versions list in `.et`
  .et
Labels: internal

#865 species url is case sensitive
  dandi/metadata.py
  dandi/tests/data/metadata/metadata2asset_3.json
  dandi/tests/test_metadata.py
Labels: patch

#870 Make navigate() and navigate_url() auto-authenticate for embargoed Dandisets
  dandi/dandiarchive.py
Labels: minor, release

#876 Use a pydantic model to store a RemoteDandiset's cached data
  dandi/dandiapi.py
Labels: internal

#853 Support Zarr directories
  dandi/cli/base.py
  dandi/cli/cmd_download.py
  dandi/cli/cmd_ls.py
  dandi/cli/cmd_upload.py
  dandi/cli/cmd_validate.py
  dandi/cli/tests/test_download.py
  dandi/consts.py
  dandi/dandiapi.py
  dandi/download.py
  dandi/exceptions.py
  dandi/files.py
  dandi/metadata.py
  dandi/misctypes.py
  dandi/support/digests.py
  dandi/tests/fixtures.py
  dandi/tests/test_dandiapi.py
  dandi/tests/test_dandiarchive.py
  dandi/tests/test_delete.py
  dandi/tests/test_download.py
  dandi/tests/test_files.py
  dandi/tests/test_helpers.py
  dandi/tests/test_keyring.py
  dandi/tests/test_upload.py
  dandi/tests/test_validate.py
  dandi/upload.py
  dandi/utils.py
  dandi/validate.py
  docs/source/cmdline/download.rst
  docs/source/cmdline/upload.rst
  docs/source/cmdline/validate.rst
  docs/source/modref/files.rst
  docs/source/modref/index.rst
  docs/source/modref/misctypes.rst
  setup.cfg
  tools/update-assets-on-server
Labels: minor, priority-high

#886 Mark a test with missing `skipif_no_network` marker
  dandi/tests/test_metadata.py
Labels: tests

#885 Delete functions (get_asset_metadata, find_dandi_files) obsoleted by PR #853
  dandi/metadata.py
  dandi/utils.py
Labels: internal

#874 Add `new_dandiset` fixture
  dandi/tests/fixtures.py
  dandi/tests/test_dandiapi.py
  dandi/tests/test_download.py
  dandi/tests/test_files.py
  dandi/tests/test_upload.py
Labels: tests

#877 Enable type-checking
  .github/workflows/typing.yml
  dandi/cli/base.py
  dandi/consts.py
  dandi/dandiapi.py
  dandi/dandiarchive.py
  dandi/delete.py
  dandi/download.py
  dandi/files.py
  dandi/metadata.py
  dandi/misctypes.py
  dandi/support/digests.py
  dandi/tests/fixtures.py
  dandi/tests/test_download.py
  dandi/utils.py
  setup.cfg
  tox.ini
Labels: tests

#891 Fix neural data type to metadata extractor
  dandi/metadata.py
  dandi/tests/test_metadata.py
Labels: patch

#888 Organize & fine-tune dandi.dandiapi Sphinx docs
  .github/workflows/test.yml
  dandi/dandiapi.py
  docs/source/examples/dandiapi-example.py
  docs/source/modref/dandiapi.rst
  tox.ini
Labels: documentation

#887 Add type-annotations to various files
  dandi/conftest.py
  dandi/dandiarchive.py
  dandi/dandiset.py
  dandi/delete.py
  dandi/download.py
  dandi/exceptions.py
  dandi/keyring.py
  dandi/metadata.py
  dandi/pynwb_utils.py
  dandi/tests/fixtures.py
  dandi/tests/test_dandiapi.py
  dandi/tests/test_dandiarchive.py
  dandi/tests/test_dandiset.py
  dandi/tests/test_delete.py
  dandi/tests/test_download.py
  dandi/tests/test_fixtures.py
  dandi/tests/test_keyring.py
  dandi/tests/test_metadata.py
  dandi/tests/test_organize.py
  dandi/tests/test_pynwb_utils.py
  dandi/tests/test_upload.py
  dandi/tests/test_utils.py
  dandi/upload.py
  dandi/utils.py
  dandi/validate.py
Labels: internal

#894 Make `get_raw_digest()` actually default to the proper digest type for Zarrs
  dandi/dandiapi.py
Labels: patch
