Repository dandi/dandi-cli, pull requests merged in 2022-08, with the labels that each got.

#1088 Factor out common fields in nwb2asset() and get_default_metadata()
  dandi/metadata.py
  dandi/tests/test_metadata.py
Labels: internal

#1008 BF: guard download_generator to not propagate errors
  dandi/download.py
  dandi/metadata.py
  dandi/support/typing.py
  dandi/tests/fixtures.py
  dandi/tests/test_download.py
  dandi/upload.py
Labels: UX, patch

#1098 Add examples to `dandi move` docs
  dandi/cli/cmd_move.py
  docs/source/cmdline/move.rst
Labels: documentation, cmd-move

#1076 Add classes for BIDS assets
  dandi/cli/tests/test_ls.py
  dandi/consts.py
  dandi/delete.py
  dandi/files.py
  dandi/files/__init__.py
  dandi/files/_private.py
  dandi/files/bases.py
  dandi/files/bids.py
  dandi/files/zarr.py
  dandi/metadata.py
  dandi/tests/test_files.py
  dandi/tests/test_upload.py
  dandi/upload.py
  setup.cfg
Labels: minor, BIDS, Python API

#1100 Update video NWB fixtures for next pynwb version
  dandi/tests/fixtures.py
Labels: tests

#1102 Tell codespell to ignore "bu" strings in tests
  .codespellignore
Labels: release, tests

#1101 Add support for age range
  dandi/metadata.py
  dandi/tests/test_metadata.py
Labels: patch

#1103 Update test.yml to use ubuntu-latest
  .github/workflows/test.yml
Labels: tests

#1106 DOC: minor - boost copyright years in the docs
  docs/source/conf.py
Labels: documentation, release

#1107 get_content_url(): If a HEAD fails, return the failing URL
  dandi/dandiapi.py
  dandi/tests/test_dandiapi.py
Labels: patch, Python API
