Repository dandi/dandi-cli, pull requests merged in 2022-10, with the labels that each got.

#1121 Pull latest Docker images before spinning up Compose
  dandi/tests/fixtures.py
Labels: tests

#1122 increase number of trials in docker_compose_setup to 25
  dandi/tests/fixtures.py
Labels: tests

#1125 Update client-side publication workflow
  dandi/dandiapi.py
  dandi/tests/test_dandiapi.py
Labels: release, internal

#1132 Make `dandi ls` properly detect embargoed Dandisets
  dandi/cli/cmd_ls.py
Labels: patch, cmd-ls

#1135 Update GitHub Actions action versions
  .github/dependabot.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/typing.yml
Labels: internal

#1136 Simplify implementations of `get_asset()` methods
  dandi/dandiapi.py
Labels: internal

#1138 Make internal Zarr-checksumming tree types support empty Zarrs
  dandi/cli/tests/test_digest.py
  dandi/support/digests.py
  dandi/support/tests/test_digests.py
Labels: release, internal

#1123 adding testing instructions
  DEVELOPMENT.md
Labels: documentation

#1139 Don't try to cancel failed Zarr uploads twice
  dandi/files/zarr.py
Labels: patch

#1141 Add `DANDI_TESTS_PULL_DOCKER_COMPOSE` envvar
  DEVELOPMENT.md
  dandi/tests/fixtures.py
Labels: release, tests

#1142 Make `list_paths()` include dotfiles
  dandi/utils.py
Labels: internal

#1145 Installing hdf5 for Python 3.10 is no longer needed
  .github/workflows/test.yml
Labels: tests

#1104 Structured validation results
  dandi/bids_utils.py
  dandi/cli/cmd_validate.py
  dandi/cli/tests/test_cmd_validate.py
  dandi/files/bases.py
  dandi/files/bids.py
  dandi/files/zarr.py
  dandi/pynwb_utils.py
  dandi/tests/fixtures.py
  dandi/tests/test_files.py
  dandi/tests/test_validate.py
  dandi/validate.py
  dandi/validate_types.py
  setup.cfg
Labels: minor, cmd-validate, Python API

#1147 Exclude special dotfiles from Zarrs
  dandi/cli/tests/test_digest.py
  dandi/download.py
  dandi/files/_private.py
  dandi/files/zarr.py
  dandi/support/digests.py
  dandi/support/threaded_walk.py
  dandi/tests/test_download.py
  dandi/tests/test_files.py
  dandi/utils.py
Labels: minor, cmd-upload, cmd-download, cmd-digest, zarr

#1148 Fixed logic and commented a temporarily broken BIDS (lacking README) dataset
  dandi/tests/fixtures.py
  dandi/tests/test_validate.py
Labels: tests
