Repository dandi/dandi-cli, pull requests merged in 2022-05, with the labels that each got.

#994 Setting version to min version if not available
  dandi/bids_validator_xs.py
Labels: patch, severity-minor, BIDS

#1001 ENH: delete - allow to specify --force in CLI
  dandi/cli/cmd_delete.py
  docs/source/cmdline/delete.rst
Labels: patch

#992 Logging validation warnings and errors
  dandi/bids_validator_xs.py
  dandi/cli/cmd_validate.py
  dandi/cli/tests/test_cmd_validate.py
  dandi/tests/test_bids_validator_xs.py
Labels: release, BIDS

#1010 Removing trace from previous commit
  dandi/metadata.py
Labels: patch

#1013 Fix error message formatting
  dandi/download.py
Labels: patch

#1021 Fetch paginated results concurrently
  .github/workflows/test.yml
  dandi/dandiapi.py
  dandi/tests/test_dandiapi.py
  dandi/tests/test_utils.py
  dandi/utils.py
  tox.ini
Labels: release, performance
