Repository dandi/dandi-cli, pull requests merged in 2022-11, with the labels that each got.

#1150 Remove Parameters description from docstring used by click
  dandi/cli/cmd_validate.py
Labels: documentation

#1149 Use cached namespace validation
  dandi/pynwb_utils.py
Labels: patch

#1157 Update `test_validate_nwb_path_grouping` test
  dandi/cli/tests/test_cmd_validate.py
Labels: tests

#1156 Fix typing error under mypy 0.990
  dandi/files/_private.py
Labels: tests

#1161 No longer mark `test_rename_type_mismatch` as xfailing
  dandi/tests/test_dandiapi.py
Labels: tests

#1166 Corrected reporting function logic to complete group message variable
  dandi/cli/cmd_validate.py
Labels: patch
