Repository dandi/dandi-cli, pull requests merged in 2022-07, with the labels that each got.

#1035 Reuse "loose" Zarrs that conflict with uploaded path
  dandi/files.py
  dandi/tests/test_upload.py
Labels: minor

#1040 Make `test_move_command_too_few_paths` support `DANDI_DEVEL=1`
  dandi/cli/tests/test_move.py
Labels: release, tests

#1041 Better cancellation of Zarr uploads
  dandi/cli/cmd_service_scripts.py
  dandi/cli/command.py
  dandi/cli/tests/test_service_scripts.py
  dandi/files.py
  docs/source/cmdline/service-scripts.rst
Labels: minor, release

#981 Add `get_assets_by_glob()`
  dandi/dandiapi.py
  dandi/tests/test_dandiapi.py
Labels: minor, release

#1048 Retry Zarr entry uploads that fail with "header ... implies functionality ... not implemented"
  dandi/dandiapi.py
  dandi/files.py
Labels: patch, release

#1052 Clone entire repo in "Lint" action
  .github/workflows/lint.yml
Labels: internal

#1011 Built-in BIDS support for `dandi upload`
  dandi/bids_utils.py
  dandi/bids_validator_xs.py
  dandi/cli/cmd_validate.py
  dandi/tests/fixtures.py
  dandi/tests/test_upload.py
  dandi/upload.py
  dandi/validate.py
Labels: enhancement, minor, BIDS, cmd-upload

#1056 Replace numpy.asscalar() with numpy.ndarray.item()
  dandi/pynwb_utils.py
Labels: release, internal

#1064 dandi move: Include all mismatches in error messages
  dandi/move.py
  dandi/tests/test_move.py
Labels: patch, cmd-move

#1062 Mention in help text that 'draft' is not supported in DANDI:<dandiset>/<version>
  dandi/dandiarchive.py
Labels: documentation

#1063 dandi move: Fix resolution of nonexistent dests when in a subdirectory
  dandi/move.py
  dandi/tests/test_move.py
Labels: patch, release, cmd-move

#1087 Remove redirector from Docker Compose setup
  dandi/tests/data/dandiarchive-docker/docker-compose.yml
  dandi/tests/fixtures.py
Labels: tests

#1080 User notification if datasets are invalid.
  dandi/tests/fixtures.py
  dandi/tests/test_upload.py
  dandi/upload.py
Labels: patch
