Repository dandi/dandi-cli, pull requests merged in 2023-12, with the labels that each got.

#1376 Properly open filehandles for `RemoteReadableAsset`s
  dandi/misctypes.py
  dandi/tests/test_dandiapi.py
Labels: patch, release

#1377 Minor docs update for `dandi validate`
  .gitignore
  README.md
  dandi/cli/cmd_validate.py
  docs/source/cmdline/validate.rst
Labels: documentation

#1374 Double-check file sizes before & after uploading
  dandi/files/bases.py
  dandi/files/zarr.py
  dandi/tests/test_utils.py
  dandi/utils.py
Labels: patch

#1382 Minor update to `organize` docstring
  README.md
  dandi/cli/cmd_organize.py
Labels: documentation

#1384 `dandi download dandi://…/dandiset.yaml` now downloads `dandiset.yaml`
  dandi/download.py
  dandi/tests/test_download.py
Labels: minor, cmd-download
