Repository dandi/dandi-cli, pull requests merged in 2023-02, with the labels that each got.

#1201 Pass $USER to tox envs
  tox.ini
Labels: internal

#1207 Fix type errors; unbound mypy
  dandi/metadata.py
  tox.ini
Labels: tests

#1204 Improve messages displayed when an upload fails
  dandi/exceptions.py
  dandi/tests/test_upload.py
  dandi/upload.py
Labels: UX, patch, cmd-upload

#1210 Make `RemoteDandiset.get_version()` return a `VersionInfo` instance with validation error fields
  dandi/dandiapi.py
  docs/source/modref/dandiapi.rst
Labels: patch, Python API

#1209 BF+RF validation
  dandi/files/bases.py
  dandi/files/zarr.py
  dandi/misctypes.py
  dandi/pynwb_utils.py
Labels: minor, cmd-validate

#1202 Update for new Zarr upload procedure; remove no longer needed `service-scripts`
  README.md
  dandi/cli/cmd_service_scripts.py
  dandi/cli/command.py
  dandi/cli/tests/test_service_scripts.py
  dandi/dandiapi.py
  dandi/files/zarr.py
  dandi/support/digests.py
  docs/source/cmdline/service-scripts.rst
  setup.cfg
Labels: minor, release, cmd-upload, zarr, released

#1213 Restore testing against Windows with Python 3.10
  .github/workflows/test.yml
  tox.ini
Labels: tests

#1215 Update for fix to Zarr upload procedure
  dandi/files/zarr.py
Labels: patch, release, cmd-upload, zarr

#1143 Test against Python 3.11
  .github/workflows/test.yml
  setup.cfg
  tox.ini
Labels: tests

#1200 List in documentation the "high level" interfaces corresponding to CLI
  dandi/delete.py
  dandi/validate.py
  docs/source/cmdline/index.rst
  docs/source/modref/index.rst
Labels: documentation

#1216 Metadata: add extraction of strain from nwb files
  dandi/metadata.py
  dandi/tests/data/metadata/metadata2asset_3.json
  dandi/tests/test_metadata.py
Labels: patch

#1220 Filter out pyout logs from logfile by default
  dandi/cli/command.py
Labels: patch

#1225 Fix tests: avoid obolibrary (for now) and pynwb 2.3.0 (forever)
  .github/workflows/test.yml
  dandi/tests/test_metadata.py
  setup.cfg
  tox.ini
Labels: tests

#1221 Don't even test for `cp --reflink` support on Windows
  dandi/utils.py
Labels: patch, cmd-organize

#1226 Revert "Temporarily disable all tests which talk to obolibrary" - ontobee said to be back
  .github/workflows/test.yml
Labels: tests

#1227 Update `parse_purlobourl()` test for change to rat metadata
  dandi/tests/test_metadata.py
Labels: tests

#1224 Added distribution badge (sadly only one ATM)
  README.md
Labels: documentation

#1228 BF: add missing f- for a string
  dandi/files/__init__.py
Labels: UX, patch

#1222 Inform user with a warning in case of jobs > 1 but non pyout format
  dandi/download.py
Labels: UX, patch

#1214 Support re-extracting metadata from remote assets
  .github/workflows/test.yml
  dandi/dandiapi.py
  dandi/files/bases.py
  dandi/files/bids.py
  dandi/metadata.py
  dandi/misctypes.py
  dandi/pynwb_utils.py
  dandi/tests/test_metadata.py
  setup.cfg
  tox.ini
Labels: minor
