Repository dandi/dandi-cli, pull requests merged in 2023-11, with the labels that each got.

#1337 Re-record VCR tapes using newer versions of libraries
  dandi/cli/tests/data/update_dandiset_from_doi/biorxiv.vcr.yaml
  dandi/cli/tests/data/update_dandiset_from_doi/elife.vcr.yaml
  dandi/cli/tests/data/update_dandiset_from_doi/jneurosci.vcr.yaml
  dandi/cli/tests/data/update_dandiset_from_doi/nature.vcr.yaml
  dandi/cli/tests/data/update_dandiset_from_doi/neuron.vcr.yaml
  dandi/cli/tests/test_service_scripts.py
Labels: tests

#1336 typing: Account for the fact that requests.HTTPError .response migth be None now
  dandi/dandiapi.py
  dandi/dandiarchive.py
  dandi/download.py
  dandi/files/bases.py
  dandi/files/zarr.py
Labels: release, internal

#1341 Expose number of jobs to organize
  dandi/cli/cmd_organize.py
  dandi/organize.py
  dandi/tests/test_organize.py
Labels: minor

#1342 Don't use buggy version of `responses`
  setup.cfg
Labels: release, tests

#1344 Move words ignored by codespell from `.codespellignore` to `setup.cfg`
  .codespellignore
  setup.cfg
Labels: internal

#1345 Replace appdirs with platformdirs
  dandi/cli/command.py
  setup.cfg
  tox.ini
Labels: dependencies

#1343 Modernize type annotations and improve mypy config
  dandi/cli/__init__.py
  dandi/cli/cmd_move.py
  dandi/cli/cmd_validate.py
  dandi/cli/tests/test_cmd_ls.py
  dandi/cli/tests/test_command.py
  dandi/cli/tests/test_download.py
  dandi/cli/tests/test_instances.py
  dandi/cli/tests/test_move.py
  dandi/cli/tests/test_service_scripts.py
  dandi/conftest.py
  dandi/consts.py
  dandi/dandiapi.py
  dandi/dandiarchive.py
  dandi/dandiset.py
  dandi/delete.py
  dandi/download.py
  dandi/exceptions.py
  dandi/files/__init__.py
  dandi/files/_private.py
  dandi/files/bases.py
  dandi/files/bids.py
  dandi/files/zarr.py
  dandi/keyring.py
  dandi/metadata.py
  dandi/misctypes.py
  dandi/move.py
  dandi/organize.py
  dandi/pynwb_utils.py
  dandi/support/digests.py
  dandi/support/threaded_walk.py
  dandi/support/typing.py
  dandi/tests/fixtures.py
  dandi/tests/test_dandiapi.py
  dandi/tests/test_delete.py
  dandi/tests/test_download.py
  dandi/tests/test_files.py
  dandi/tests/test_keyring.py
  dandi/tests/test_metadata.py
  dandi/tests/test_move.py
  dandi/tests/test_organize.py
  dandi/tests/test_pynwb_utils.py
  dandi/tests/test_upload.py
  dandi/tests/test_utils.py
  dandi/upload.py
  dandi/utils.py
  dandi/validate.py
  dandi/validate_types.py
  setup.cfg
Labels: internal, code quality

#1350 Run `pyupgrade --py38-plus` on source
  dandi/cli/cmd_ls.py
  dandi/cli/command.py
  dandi/cli/formatter.py
  dandi/dandiapi.py
  dandi/download.py
  dandi/due.py
  dandi/organize.py
  dandi/pynwb_utils.py
  dandi/support/pyout.py
  dandi/tests/fixtures.py
  dandi/tests/skip.py
  dandi/tests/test_keyring.py
  dandi/tests/test_upload.py
  dandi/utils.py
Labels: internal, code quality

#1349 Use dataclass instead of `auto_repr`
  dandi/download.py
  dandi/support/digests.py
  dandi/utils.py
Labels: internal, code quality

#1348 Remove `_order_` attribute from `Severity` enum
  dandi/validate_types.py
Labels: internal, code quality

#1347 Replace `_pytest` imports with modern `pytest` imports
  dandi/conftest.py
  dandi/tests/fixtures.py
Labels: internal, code quality

#1356 Convert dandiarchive URL classes from pydantic models to dataclasses
  dandi/consts.py
  dandi/dandiarchive.py
Labels: internal, code quality

#1359 Fix typing error
  dandi/cli/cmd_move.py
Labels: tests

#1355 find_files: Simplify check for VCS and DataLad paths
  dandi/utils.py
Labels: internal, code quality

#1320 Install also hdmf from git in the dev-deps CI run
  .github/workflows/test.yml
Labels: tests

#1357 Replace magic string arguments with enums
  dandi/cli/cmd_digest.py
  dandi/cli/cmd_download.py
  dandi/cli/cmd_ls.py
  dandi/cli/cmd_move.py
  dandi/cli/cmd_organize.py
  dandi/cli/cmd_service_scripts.py
  dandi/cli/cmd_upload.py
  dandi/cli/tests/test_download.py
  dandi/consts.py
  dandi/download.py
  dandi/files/bases.py
  dandi/files/bids.py
  dandi/files/zarr.py
  dandi/metadata/__init__.py
  dandi/metadata/core.py
  dandi/metadata/nwb.py
  dandi/metadata/util.py
  dandi/move.py
  dandi/organize.py
  dandi/support/digests.py
  dandi/tests/fixtures.py
  dandi/tests/test_download.py
  dandi/tests/test_metadata.py
  dandi/tests/test_move.py
  dandi/tests/test_organize.py
  dandi/tests/test_upload.py
  dandi/upload.py
  dandi/utils.py
  setup.cfg
Labels: enhancement, Python API, code quality

#1346 Remove unused configuration settings
  Makefile
  dandi/dandiarchive.py
  setup.cfg
  tox.ini
Labels: internal, code quality

#1330 Add Python 3.12 to supported versions and test against on GitHub Actions; upgrade versioneer
  .gitattributes
  .github/workflows/test.yml
  dandi/_version.py
  dandi/cli/command.py
  dandi/utils.py
  setup.cfg
  tox.ini
  versioneer.py
Labels: patch

#1365 Update for `zarr_checksum` 0.2.12
  dandi/files/zarr.py
  dandi/support/digests.py
  setup.cfg
Labels: release, dependencies

#1368 Move imports in functions to top level or annotate why they can't be moved
  dandi/cli/cmd_digest.py
  dandi/cli/cmd_download.py
  dandi/cli/cmd_ls.py
  dandi/cli/cmd_shell_completion.py
  dandi/cli/cmd_upload.py
  dandi/cli/cmd_validate.py
  dandi/cli/command.py
  dandi/cli/formatter.py
  dandi/cli/tests/test_cmd_validate.py
  dandi/dandiapi.py
  dandi/delete.py
  dandi/download.py
  dandi/files/bases.py
  dandi/files/zarr.py
  dandi/metadata/nwb.py
  dandi/misctypes.py
  dandi/move.py
  dandi/organize.py
  dandi/pynwb_utils.py
  dandi/tests/fixtures.py
  dandi/tests/test_download.py
  dandi/upload.py
  dandi/utils.py
Labels: internal, code quality

#1369 Set 30-second connect & read timeout when downloading files
  dandi/consts.py
  dandi/dandiapi.py
  dandi/download.py
Labels: patch

#1370 Repeatedly double-check return values of zero when spying on `super_len()`
  dandi/upload.py
Labels: patch
