Repository dandi/dandi-cli, pull requests merged in 2023-04, with the labels that each got.

#1254 enh: add cellline parsing
  dandi/metadata.py
  dandi/tests/data/metadata/metadata2asset_cellline.json
  dandi/tests/test_metadata.py
Labels: minor

#1264 Log more information about retried HTTP requests
  dandi/consts.py
  dandi/dandiapi.py
  dandi/tests/test_dandiapi.py
Labels: patch, release

#1267 Log results of `requests.utils.super_len()` when `DANDI_DEVEL_INSTRUMENT_REQUESTS_SUPERLEN` is set
  .github/workflows/test.yml
  DEVELOPMENT.md
  dandi/upload.py
Labels: patch

#1260 validate: resolved issues with relative path input
  dandi/tests/test_validate.py
  dandi/validate.py
Labels: patch

#1272 Fix `test_validate_relative_path`
  dandi/tests/test_validate.py
Labels: tests

#1274 Make test NFS-safe
  dandi/tests/test_files.py
Labels: tests

#1277 Add configuration for log buckets in testing
  dandi/tests/data/dandiarchive-docker/docker-compose.yml
Labels: tests

#1276 C elegans
  dandi/metadata.py
  dandi/tests/test_metadata.py
Labels: patch

#1278 Support asset path globs in `dandi download`
  dandi/cli/cmd_download.py
  dandi/cli/tests/test_download.py
  dandi/dandiarchive.py
  dandi/download.py
  dandi/tests/fixtures.py
  dandi/tests/test_dandiarchive.py
  dandi/tests/test_download.py
  docs/source/cmdline/download.rst
  docs/source/ref/urls.rst
Labels: minor, cmd-download

#1282 Explicitly open h5py.File as read-only where we read it
  dandi/pynwb_utils.py
Labels: patch, release
