Repository dandi/dandi-cli, pull requests merged in 2023-05, with the labels that each got.

#1285 Use `inspect_nwbfile()` instead of `inspect_nwb()`; address bug in recent `ruamel.yaml` versions
  dandi/files/bases.py
  dandi/metadata.py
  dandi/organize.py
  setup.cfg
Labels: patch

#1287 Cancel any still-running tests when pushing to a branch or PR
  .github/workflows/test.yml
Labels: internal

#1290 Retry test that intermittently fails on NFS
  dandi/tests/test_files.py
  setup.cfg
Labels: tests

#1283 Add `dandi service-scripts update-dandiset-from-doi` command
  DEVELOPMENT.md
  dandi/cli/base.py
  dandi/cli/cmd_download.py
  dandi/cli/cmd_service_scripts.py
  dandi/cli/tests/data/update_dandiset_from_doi/biorxiv.json
  dandi/cli/tests/data/update_dandiset_from_doi/biorxiv.vcr.yaml
  dandi/cli/tests/data/update_dandiset_from_doi/elife.json
  dandi/cli/tests/data/update_dandiset_from_doi/elife.vcr.yaml
  dandi/cli/tests/data/update_dandiset_from_doi/jneurosci.json
  dandi/cli/tests/data/update_dandiset_from_doi/jneurosci.vcr.yaml
  dandi/cli/tests/data/update_dandiset_from_doi/nature.json
  dandi/cli/tests/data/update_dandiset_from_doi/nature.vcr.yaml
  dandi/cli/tests/data/update_dandiset_from_doi/neuron.json
  dandi/cli/tests/data/update_dandiset_from_doi/neuron.vcr.yaml
  dandi/cli/tests/test_download.py
  dandi/cli/tests/test_service_scripts.py
  dandi/tests/fixtures.py
  docs/source/cmdline/service-scripts.rst
  setup.cfg
Labels: minor

#1286 Support uploading a subset of files from a BIDS dataset
  dandi/cli/cmd_ls.py
  dandi/dandiset.py
  dandi/files/bases.py
  dandi/tests/test_upload.py
  dandi/tests/test_utils.py
  dandi/upload.py
  dandi/utils.py
Labels: minor, release, cmd-upload

#1243 Bidsschematools 0.7.0 API usage update
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/typing.yml
  .readthedocs.yaml
  dandi/validate.py
  setup.cfg
Labels: release, dependencies

#1296 Remove Python 3.7-specific code
  dandi/cli/cmd_instances.py
  dandi/support/typing.py
  dandi/utils.py
Labels: internal

#1292 Don't treat certain broken symlinks as absent files
  dandi/dandiset.py
  dandi/files/__init__.py
  dandi/files/bids.py
  dandi/files/zarr.py
  dandi/move.py
  dandi/organize.py
  dandi/upload.py
  dandi/utils.py
Labels: patch

#1299 Drop dependency on importlib-metadata backport for Python 3.7
  setup.cfg
Labels: dependencies

#1301 Fix test for newer hdf5
  dandi/tests/test_files.py
Labels: tests
