Repository dandi/dandi-cli, pull requests merged in 2023-10, with the labels that each got.

#1333 Ignore unclosed connection resource warning from VCR
  tox.ini
Labels: tests

#1334 codespell: tuneup of config and some new typos detected fixes
  dandi/tests/data/metadata/dandimeta_migration.new.json
  docs/design/python-api-1.md
  setup.cfg
  tools/update-assets-on-server
Labels: internal

#1338 Minor documentation tune up
  dandi/__init__.py
  docs/source/conf.py
Labels: documentation

#1305 `?location` parameter in URLs can only point to a folder
  dandi/dandiarchive.py
  dandi/tests/test_dandiarchive.py
  docs/source/ref/urls.rst
Labels: minor, Python API

#1340 Add missing term in ETA calculation
  dandi/download.py
  dandi/tests/test_download.py
Labels: patch
