Repository dandi/dandi-cli, pull requests merged in 2023-01, with the labels that each got.

#1184 Don't warn on unexpected formats for "next" page URLs
  dandi/dandiapi.py
Labels: patch

#1186 Fail upload only for validation ERRORs and not necessarily WARNINGs or HINTs + log all errors
  dandi/upload.py
Labels: patch, release

#1193 Further improve README.md: point to specific sections of handbook, remove lengthy `dandi ls --help` example
  README.md
Labels: documentation

#1183 Joint BIDS-NWB metadata extraction.
  dandi/files/bids.py
  dandi/metadata.py
  dandi/tests/fixtures.py
  dandi/tests/test_metadata.py
Labels: tests, BIDS, NWB
