Repository dandi/dandi-cli, pull requests merged in 2024-11, with the labels that each got.

#1524 fix: replace dandi-api link with dandi-archive
  DEVELOPMENT.md
Labels: documentation

#1527 Include LINC API as a supported instance type for DANDI CLI
  dandi/cli/tests/test_instances.py
  dandi/consts.py
  dandi/tests/test_dandiarchive.py
  docs/source/cmdline/instances.rst
Labels: patch

#1509 download: more consistent and exhaustive logging, new `DANDI_DEVEL_AGGRESSIVE_RETRY` mode, respect (?) Retry-After
  DEVELOPMENT.md
  dandi/cli/command.py
  dandi/cli/tests/test_service_scripts.py
  dandi/dandiapi.py
  dandi/download.py
  dandi/tests/test_download.py
  setup.cfg
Labels: minor, release, cmd-download

#1530 Rename `file` key to codecov-action to `files`
  .github/workflows/test.yml
Labels: tests

#1533 Specify custom ulimit on nofiles to prevent infinite loop by billiard
  dandi/tests/data/dandiarchive-docker/docker-compose.yml
Labels: tests

#1532 add one photon to metadata dict
  dandi/metadata/util.py
Labels: patch

#1531 tests: update tests docker-compose with few changes from dandi-archive
  dandi/tests/data/dandiarchive-docker/docker-compose.yml
Labels: DX, tests

#1538 Fix `PrivateAttr` usage
  dandi/dandiapi.py
Labels: patch

#1539 Ignore some type-checking errors under Python 3.13
  dandi/dandiarchive.py
Labels: tests

#1535 Refactor some download code for readability + ensure that we checksum resumed downloads
  dandi/download.py
  dandi/tests/test_download.py
Labels: minor, release
