Repository dandi/dandi-cli, pull requests merged in 2024-05, with the labels that each got.

#1429 ENH: add/use codespell-project/codespell-problem-matcher to annotate PRs on where typos added
  .github/workflows/lint.yml
  tox.ini
Labels: internal

#1439 Slight tune up to formatting of examples etc to harmonize appearance/make shorter
  dandi/cli/cmd_download.py
  dandi/dandiarchive.py
Labels: patch

#1440 ENH: add timeout of 300 (5 minutes) to any test running
  setup.cfg
  tox.ini
Labels: tests

#1444 Rewind filehandle request bodies before retrying requests
  dandi/dandiapi.py
Labels: patch, release, cmd-upload, zarr, HIFNI

#1443 OPT+RF of zarr downloads: do not wait for full files listing + compute %done from total zarr size
  dandi/download.py
  dandi/tests/test_download.py
Labels: patch, cmd-download, zarr
