Repository dandi/dandi-cli, pull requests merged in 2024-01, with the labels that each got.

#1385 Fix service script tests for change in autogenerated date
  dandi/cli/tests/test_service_scripts.py
Labels: tests

#1371 Adopt `dandischema.digests.zarr.get_checksum()` to dandi-cli: use zarr_checksum library constructs instead of copies in dandischema
  dandi/files/zarr.py
  dandi/support/digests.py
  dandi/support/tests/test_digests.py
Labels: internal

#1389 Minor codespell fix in a CHANGELOG entry
  CHANGELOG.md
Labels: documentation, release

#1391 Ignore irrelevant deprecation warning from pandas
  tox.ini
Labels: tests

#1392 Update zarr_checksum dependency to `~= 0.3.2`
  setup.cfg
Labels: dependencies

#1393 Update zarr_checksum dependency to `~= 0.4.0`
  setup.cfg
Labels: dependencies
