Repository dandi/dandi-cli, pull requests merged in 2024-02, with the labels that each got.

#1398 Add notes to docs about `get_metadata()` vs. `get_raw_metadata()`
  dandi/dandiapi.py
Labels: documentation

#1399 Failsafe etelemetry import
  dandi/files/bases.py
Labels: internal

#1401 Blacklist buggy nwbinspector 0.4.32
  setup.cfg
Labels: release, dependencies

#1381 Update for Pydantic v2
  dandi/cli/cmd_download.py
  dandi/cli/cmd_ls.py
  dandi/cli/cmd_service_scripts.py
  dandi/cli/tests/data/update_dandiset_from_doi/biorxiv.json
  dandi/cli/tests/data/update_dandiset_from_doi/elife.json
  dandi/cli/tests/data/update_dandiset_from_doi/jneurosci.json
  dandi/cli/tests/data/update_dandiset_from_doi/nature.json
  dandi/cli/tests/data/update_dandiset_from_doi/neuron.json
  dandi/dandiapi.py
  dandi/dandiarchive.py
  dandi/files/bases.py
  dandi/files/bids.py
  dandi/metadata/core.py
  dandi/metadata/util.py
  dandi/tests/data/metadata/metadata2asset_simple1.json
  dandi/tests/test_dandiapi.py
  dandi/tests/test_metadata.py
  dandi/upload.py
  dandi/utils.py
  setup.cfg
Labels: minor, dependencies

#1412 Report progress in deleting Zarr entries during upload
  .pre-commit-config.yaml
  dandi/files/bases.py
  dandi/files/zarr.py
  dandi/support/pyout.py
  dandi/upload.py
Labels: UX, minor, release, cmd-upload, zarr

#1414 Add arguments for API query parameters when fetching all Dandisets; support creating embargoed Dandisets
  dandi/dandiapi.py
  dandi/tests/fixtures.py
  dandi/tests/test_dandiapi.py
Labels: minor, Python API
