Repository dandi/dandi-cli, pull requests merged in 2024-12, with the labels that each got.

#1536 Do fail (raise Exception, CLI has non-0 exit) download if any of downloads fail
  dandi/download.py
  dandi/tests/test_download.py
Labels: minor, release

#1547 BF: do allow for user to specify a proper full name for "species" in metadata
  dandi/metadata/util.py
  dandi/tests/test_metadata.py
Labels: patch, release

#1550 download: provide description for an assertion error on attempts_allowed_or_not
  dandi/download.py
Labels: DX, internal

#1552 enh: log exception info (at debug) when we catch an exception in map_to_click handler
  dandi/cli/base.py
Labels: patch

#1554 Reduce messaging to pyout on progress of downloads
  dandi/download.py
  dandi/support/pyout.py
  dandi/tests/test_download.py
Labels: release, performance

#1548 Update docs to generalize from `DANDI Archive` to `DANDI instance`
  .github/workflows/test.yml
  README.md
  dandi/cli/cmd_instances.py
  dandi/cli/command.py
  dandi/cli/tests/data/update_dandiset_from_doi/biorxiv.json
  dandi/cli/tests/data/update_dandiset_from_doi/elife.json
  dandi/cli/tests/data/update_dandiset_from_doi/jneurosci.json
  dandi/cli/tests/data/update_dandiset_from_doi/nature.json
  dandi/cli/tests/data/update_dandiset_from_doi/neuron.json
  dandi/conftest.py
  dandi/dandiapi.py
  dandi/dandiarchive.py
  dandi/delete.py
  dandi/download.py
  dandi/exceptions.py
  dandi/files/__init__.py
  dandi/files/bases.py
  dandi/files/zarr.py
  dandi/organize.py
  dandi/tests/fixtures.py
  dandi/tests/test_delete.py
  docs/design/python-api-1.md
  docs/source/cmdline/dandi.rst
  docs/source/cmdline/instances.rst
  docs/source/modref/dandiapi.rst
  docs/source/modref/index.rst
  docs/source/ref/urls.rst
  setup.cfg
Labels: release, internal

#1558 Continue retrying downloads on retriable statuses
  dandi/download.py
Labels: patch, cmd-download
