Repository dandi/dandi-cli, pull requests merged in 2024-09, with the labels that each got.

#1496 Disallow hdmf 3.14.4, make organize to not parallelize for a single file, log information about all exceptions while reading metadata for organize
  dandi/organize.py
  setup.cfg
Labels: UX, patch, release, cmd-organize

#1506 Switch to python 3.9 in dev-deps CI matrix run since dev deps are now beginning to drop Python 3.8 which is EOL soon
  .github/workflows/test.yml
Labels: tests

#1502 Fixup URI scheme rendering in --help output
  dandi/dandiarchive.py
  dandi/tests/test_helptext.py
Labels: patch

#1497 Use "cache_spec:False" in our copy_nwb_file helper while exporting NWB copy
  dandi/pynwb_utils.py
Labels: internal

#1499 ENH: log dandischema version and ensure we log (consistently) path for log messages in download
  dandi/cli/command.py
  dandi/download.py
Labels: DX, patch
