Repository dandi/dandi-cli, pull requests merged in 2024-03, with the labels that each got.

#1416 Clean up URL parsing in `extract_species()`
  dandi/metadata/util.py
Labels: internal, code quality

#1415 Use `yarl` to clean up some code
  dandi/dandiapi.py
  dandi/delete.py
  dandi/tests/test_delete.py
  dandi/utils.py
  setup.cfg
Labels: dependencies, code quality

#1419 Do not allow dandischema 0.10.1 - new schema not yet supported by dandi-archive
  setup.cfg
Labels: patch, release

#1420 Revert "Do not allow dandischema 0.10.1 - new schema not yet supporteed by dandi-archive"
  setup.cfg
Labels: patch, release

#1421 Add missing command to `dandi-archive` docker compose fixture
  dandi/tests/fixtures.py
Labels: release, tests

#1423 Xfail flaky ontobee tests, unless running daily tests
  .github/workflows/test.yml
  dandi/conftest.py
  dandi/tests/test_metadata.py
Labels: tests
