Repository dandi/dandi-cli, pull requests merged in 2025-02, with the labels that each got.

#1578 Trivial word change so we can cut a release for EMBER
  README.md
Labels: patch, release

#1576 Set Content-Type when uploading certain Zarr entries
  dandi/dandiapi.py
  dandi/files/zarr.py
  dandi/tests/test_files.py
Labels: minor, cmd-upload, zarr

#1574 Do specify our copyright in LICENSE file, unify name with dandiarchive.org, make year auto update in docs
  .github/workflows/update-year.yml
  LICENSE
  docs/source/conf.py
Labels: internal

#1545 Add Python 3.13 as supported version
  .github/workflows/test.yml
  setup.cfg
Labels: patch

#1577 Enforce usage of auto (release) labels
  .github/workflows/labels.yml
Labels: internal
