Repository dandi/dandi-cli, pull requests merged in 2025-05, with the labels that each got.

#1628 BF(workaround): disallow click 8.2.0 due to regression
  setup.cfg
Labels: patch, release

#1599 Replace the use of `bidsschematools` with the use of deno-compiled BIDS validator in obtaining validation result
  dandi/bids_validator_deno/__init__.py
  dandi/bids_validator_deno/_models.py
  dandi/bids_validator_deno/_validator.py
  dandi/cli/tests/test_cmd_validate.py
  dandi/files/bids.py
  dandi/tests/test_bids_validator_deno/test_validator.py
  dandi/tests/test_upload.py
  dandi/tests/test_validate.py
  dandi/validate.py
  dandi/validate_types.py
  setup.cfg
Labels: minor, BIDS

#1630 Restrict to specific 0.11.0 dandischema so we do not upgrade to 0.11.1 which provided new dandi schema release, and limit click before 8.2.0 for now
  setup.cfg
Labels: patch, release

#1633 Add Claude Code GitHub Workflow
  .github/workflows/claude.yml
Labels: internal

#1632 Stop extensively test no longer used gui.dandiarchive.org, retry HEAD (redirects) upon requests.ConnectionError
  dandi/dandiarchive.py
  dandi/tests/test_dandiarchive.py
Labels: patch, tests

#1638 Workaround: catch AttributeError while formatting exception
  dandi/organize.py
Labels: patch
