Repository dandi/dandi-cli, pull requests merged in 2025-04, with the labels that each got.

#1601 Remove deprecated use of Pydantic per Pydantic 2.11
  dandi/metadata/util.py
Labels: patch

#1603 Download: make it retry more times and log the first error from many
  dandi/download.py
  dandi/tests/test_download.py
Labels: patch, release, cmd-download

#1514 Overhauling validation results to get them closer to cover different types of validators
  dandi/cli/tests/test_cmd_validate.py
  dandi/files/bases.py
  dandi/files/bids.py
  dandi/files/zarr.py
  dandi/organize.py
  dandi/pynwb_utils.py
  dandi/tests/test_files.py
  dandi/tests/test_validate.py
  dandi/utils.py
  dandi/validate.py
  dandi/validate_types.py
  setup.cfg
Labels: minor

#1615 Remove obsolete (without effect) piece of code in bids.py for validation
  dandi/files/bids.py
Labels: internal

#1614 Add support for validating Zarr folders with format V3 using custom walk-through and tensorstore
  dandi/files/zarr.py
  dandi/tests/data/zarr3_stores/invalid_stores/array_v3_corrupt_zarr_json.zarr/c/0/0
  dandi/tests/data/zarr3_stores/invalid_stores/array_v3_corrupt_zarr_json.zarr/c/0/1
  dandi/tests/data/zarr3_stores/invalid_stores/array_v3_corrupt_zarr_json.zarr/c/1/0
  dandi/tests/data/zarr3_stores/invalid_stores/array_v3_corrupt_zarr_json.zarr/c/1/1
  dandi/tests/data/zarr3_stores/invalid_stores/array_v3_corrupt_zarr_json.zarr/zarr.json
  dandi/tests/data/zarr3_stores/invalid_stores/arrays_in_groups_missing_zarr_json.zarr/foo/bar/z/zarr.json
  dandi/tests/data/zarr3_stores/invalid_stores/arrays_in_groups_missing_zarr_json.zarr/foo/bar/zarr.json
  dandi/tests/data/zarr3_stores/invalid_stores/arrays_in_groups_missing_zarr_json.zarr/foo/zarr.json
  dandi/tests/data/zarr3_stores/invalid_stores/arrays_in_groups_missing_zarr_json.zarr/foo1/bar1/z1/zarr.json
  dandi/tests/data/zarr3_stores/invalid_stores/arrays_in_groups_missing_zarr_json.zarr/foo1/bar1/zarr.json
  dandi/tests/data/zarr3_stores/invalid_stores/arrays_in_groups_missing_zarr_json.zarr/foo1/zarr.json
  dandi/tests/data/zarr3_stores/invalid_stores/arrays_in_groups_node_type_problem.zarr/foo/bar/z/zarr.json
  dandi/tests/data/zarr3_stores/invalid_stores/arrays_in_groups_node_type_problem.zarr/foo/bar/zarr.json
  dandi/tests/data/zarr3_stores/invalid_stores/arrays_in_groups_node_type_problem.zarr/foo/zarr.json
  dandi/tests/data/zarr3_stores/invalid_stores/arrays_in_groups_node_type_problem.zarr/foo1/bar1/z1/zarr.json
  dandi/tests/data/zarr3_stores/invalid_stores/arrays_in_groups_node_type_problem.zarr/foo1/bar1/zarr.json
  dandi/tests/data/zarr3_stores/invalid_stores/arrays_in_groups_node_type_problem.zarr/foo1/zarr.json
  dandi/tests/data/zarr3_stores/invalid_stores/arrays_in_groups_node_type_problem.zarr/zarr.json
  dandi/tests/data/zarr3_stores/invalid_stores/single_array_missing_zarr_json.zarr/c/0/0
  dandi/tests/data/zarr3_stores/invalid_stores/single_array_missing_zarr_json.zarr/c/0/1
  dandi/tests/data/zarr3_stores/invalid_stores/single_array_missing_zarr_json.zarr/c/1/0
  dandi/tests/data/zarr3_stores/invalid_stores/single_array_missing_zarr_json.zarr/c/1/1
  dandi/tests/data/zarr3_stores/invalid_stores/single_array_node_type_problem.zarr/c/0/0
  dandi/tests/data/zarr3_stores/invalid_stores/single_array_node_type_problem.zarr/c/0/1
  dandi/tests/data/zarr3_stores/invalid_stores/single_array_node_type_problem.zarr/c/1/0
  dandi/tests/data/zarr3_stores/invalid_stores/single_array_node_type_problem.zarr/c/1/1
  dandi/tests/data/zarr3_stores/invalid_stores/single_array_node_type_problem.zarr/zarr.json
  dandi/tests/data/zarr3_stores/valid_stores/arrays_in_groups.zarr/foo/bar/z/zarr.json
  dandi/tests/data/zarr3_stores/valid_stores/arrays_in_groups.zarr/foo/bar/zarr.json
  dandi/tests/data/zarr3_stores/valid_stores/arrays_in_groups.zarr/foo/zarr.json
  dandi/tests/data/zarr3_stores/valid_stores/arrays_in_groups.zarr/foo1/bar1/z1/zarr.json
  dandi/tests/data/zarr3_stores/valid_stores/arrays_in_groups.zarr/foo1/bar1/zarr.json
  dandi/tests/data/zarr3_stores/valid_stores/arrays_in_groups.zarr/foo1/zarr.json
  dandi/tests/data/zarr3_stores/valid_stores/arrays_in_groups.zarr/zarr.json
  dandi/tests/data/zarr3_stores/valid_stores/single_array.zarr/c/0/0
  dandi/tests/data/zarr3_stores/valid_stores/single_array.zarr/c/0/1
  dandi/tests/data/zarr3_stores/valid_stores/single_array.zarr/c/1/0
  dandi/tests/data/zarr3_stores/valid_stores/single_array.zarr/c/1/1
  dandi/tests/data/zarr3_stores/valid_stores/single_array.zarr/zarr.json
  dandi/tests/test_files.py
  dandi/validate_types.py
  setup.cfg
Labels: bug, enhancement, minor, release, zarr

#1619 Deduplicate validation results yield from `validate.validate()`
  dandi/validate.py
Labels: UX, patch
