Repository dandi/dandi-cli, pull requests merged in 2025-06, with the labels that each got.

#1637 Unrestrict `dandischema` version
  setup.cfg
Labels: patch, release

#1653 Expand Zarr dependency to include version 3
  setup.cfg
Labels: minor

#1656 Fix bug when running metadata extraction on BIDS with NWB
  dandi/metadata/nwb.py
Labels: bug, patch, cmd-upload, cmd-validate
