Repository dandi/dandi-cli, pull requests merged in 2025-03, with the labels that each got.

#1584 Fix support for pynwb v3 which has changed API slightly
  dandi/pynwb_utils.py
  dandi/tests/fixtures.py
  dandi/tests/test_files.py
Labels: patch, release

#1587 BF: do not provide size for dandiset.yaml (and definetely not mtime for the size)
  dandi/download.py
Labels: UX, patch, cmd-download

#1586 Reduce looping & memory usage in ProgressCombiner
  dandi/download.py
Labels: performance, cmd-download, zarr

#1590 EMBER named it sandbox already not staging
  dandi/cli/tests/test_instances.py
  dandi/consts.py
  dandi/tests/test_dandiarchive.py
  docs/source/cmdline/instances.rst
Labels: patch, release

#1589 Add ability to release upon workflow dispatch
  .autorc
  .github/workflows/release.yml
Labels: internal

#1588 Add Dandi admin email setting
  dandi/tests/data/dandiarchive-docker/docker-compose.yml
Labels: release, tests

#1591 Upgrade bidsschematools to be of 1.x series
  dandi/cli/tests/test_cmd_ls.py
  setup.cfg
Labels: patch
